apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx 
spec: # specification for deployment
  replicas: 2  # how many replicas of the pods
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:   # specification for pod
      containers:
      - name: nginx
        image: nginx:1.16
        ports:
        - containerPort: 80
      
